# Python Web App - Generated by Auto-Deploy
# Requirement: Create a simple calculator that can add subtract multiply and divide

import js
from pyodide.ffi import to_js

def init():
    """Initialize the application"""
    output = js.document.getElementById('output')
    output.textContent = 'Python environment ready! Enter your input and click Run.'

def main(user_input):
    """Main function - processes user input and returns result"""
    # TODO: Implement based on requirement
    # Create a simple calculator that can add subtract multiply and divide
    
    if not user_input:
        return 'Please enter some input'
    
    result = f'You entered: {user_input}'
    return result
